services:
  - type: web
    name: frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://<tu-dominio-del-backend>.onrender.com"