services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: FRONTEND_URL
        value: "https://https://chat-sapito-2.onrender.com/.com"
