services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: FRONTEND_URL
        value: "https://<tu-dominio-del-frontend>.onrender.com"
